# Generated by Django 4.2.6 on 2024-01-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_parking_plaza_parkingplaza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'global_configuration',
            },
        ),
    ]
