# Generated by Django 4.2.6 on 2024-01-18 06:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0003_globalconfiguration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parking_Plaza_Log',
            new_name='ParkingPlazaLog',
        ),
        migrations.AlterModelTable(
            name='parkingplazalog',
            table='ParkingPlazaLog',
        ),
    ]
