# Generated by Django 4.2.6 on 2024-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_globalconfiguration_table_alter_vehicle_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplaza',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
