# Generated by Django 4.2.6 on 2024-01-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_parkingplaza_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingvehicle',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parkingvehicle',
            name='check_out_time',
            field=models.TimeField(),
        ),
    ]
