# Generated by Django 4.2.6 on 2024-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_parkingvehicle_check_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingvehicle',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingvehicle',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
