# Generated by Django 4.2.6 on 2024-01-19 07:39

from django.db import migrations, models
import parking.models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_alter_parkingvehicle_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.FileField(blank=True, null=True, upload_to=parking.models.save_vehicle_image),
        ),
    ]
