# Generated by Django 4.2.6 on 2024-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplaza',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
