# Generated by Django 4.2.6 on 2024-01-22 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0011_alter_parkingplaza_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingvehicle',
            name='check_in_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_checked_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingvehicle',
            name='check_in_plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaza_of_vehicles', to='parking.parkingplaza'),
        ),
    ]
