# Generated by Django 4.2.6 on 2024-01-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='auth_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterModelTable(
            name='access',
            table='User_Access',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
        migrations.CreateModel(
            name='User_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'On Leave')], max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=155, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Attendance',
            },
        ),
    ]
