# Generated by Django 4.2.6 on 2024-01-16 05:49

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_users_auth_key_alter_access_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.save_profile_image),
        ),
    ]
