# Generated by Django 4.2.6 on 2024-01-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_users_profile_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
