# Generated by Django 4.2.6 on 2024-01-16 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_role_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Attendance',
            new_name='UserAttendance',
        ),
        migrations.AddField(
            model_name='users',
            name='register_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='register_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='hired_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='hired_time',
            field=models.TimeField(),
        ),
        migrations.AlterModelTable(
            name='userattendance',
            table='UserAttendance',
        ),
    ]
