# Generated by Django 4.2.6 on 2024-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'On Leave')], default='present', max_length=20),
        ),
    ]
