# Generated by Django 4.2.6 on 2024-01-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave')], default='present', max_length=20),
        ),
    ]
