# Generated by Django 4.2.6 on 2024-01-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_userattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cnic',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
