# Generated by Django 4.2.6 on 2024-01-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_users_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
