# Generated by Django 4.2.6 on 2024-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userattendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
